apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault-secretstore
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: "http://vault-lb:8200"
    - name: vaultTokenMountPath
      value: "/vault-token/token"
    - name: vaultKVVersion
      value: "v2"
    - name: vaultKVUsePrefix
      value: "false"
    - name: enginePath
      value: "applications/data"
