apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault-secretstore
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: "http://vault-lb:8200"
    - name: vaultTokenMountPath
      value: "/vault-token"
    - name: vaultToken
      value: ""  # Will be populated from /vault-token/token file
    - name: vaultKVPrefix
      value: "applications"
    - name: vaultKVVersion
      value: "v2"
    - name: enginePath
      value: "applications"
